SOURCE_DIR=	..
SOURCE_BUILD=	$(SOURCE_DIR)/build

## ======================================================================

DIRS=

BUILD_TARGETS=		sav-notify.exe
BUILD_TARGETS_POST=

INSTALL_DIR=		$(SAMBA_DATADIR)/bin
INSTALL_EXES=		$(BUILD_TARGETS)

## ======================================================================

include $(SOURCE_BUILD)/Makefile.common

install:: install-exes

