language: c
dist: trusty

sudo: true

cache: ccache

# Everything except samba and ctdb (long tests)
env:
  - TASK=samba-xc
  - TASK=samba-ctdb
  - TASK=samba-libs
  - TASK=samba-static
  - TASK=samba-o3
  - TASK=ldb
  - TASK=tdb
  - TASK=talloc
  - TASK=replace
  - TASK=tevent
  - TASK=pidl

# Fail everything after the first job fails
matrix:
  fast_finish: true

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install --assume-yes acl attr autoconf bison build-essential debhelper dnsutils docbook-xml docbook-xsl flex gdb git krb5-user libacl1-dev libaio-dev libattr1-dev libblkid-dev libbsd-dev libcap-dev libcups2-dev libgnutls-dev libgpgme11-dev libldap2-dev libncurses5-dev libpam0g-dev libparse-yapp-perl libpopt-dev libreadline-dev perl perl-modules pkg-config python-crypto python-dev python-dnspython python-gpgme python3-crypto python3-dev python3-dnspython python3-gpgme realpath screen xsltproc zlib1g-dev

script:
 - git fetch --unshallow
 - ./script/autobuild.py --tail --testbase=/tmp $TASK
