#!/usr/bin/env python

bld.RECURSE('docs-xml')

VFS_SFV_CLAMAV_SRC = '''source3/modules/vfs_virusfilter_utils.c source3/modules/vfs_virusfilter_clamav.c'''
VFS_SFV_FSECURE_SRC = '''source3/modules/vfs_virusfilter_utils.c source3/modules/vfs_virusfilter_fsav.c'''
VFS_SFV_SOPHOS_SRC = '''source3/modules/vfs_virusfilter_utils.c source3/modules/vfs_virusfilter_sophos.c'''

bld.SAMBA3_MODULE('vfs_virusfilter_clamav',
                 subsystem='vfs',
                 source=VFS_SFV_CLAMAV_SRC,
                 deps='samba-util',
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('vfs_virusfilter_clamav'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('vfs_virusfilter_clamav'))
bld.SAMBA3_MODULE('vfs_virusfilter_fsav',
                 subsystem='vfs',
                 source=VFS_SFV_FSECURE_SRC,
                 deps='samba-util',
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('vfs_virusfilter_fsav'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('vfs_virusfilter_fsav'))
bld.SAMBA3_MODULE('vfs_virusfilter_sophos',
                 subsystem='vfs',
                 source=VFS_SFV_SOPHOS_SRC,
                 deps='samba-util',
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('vfs_virusfilter_sophos'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('vfs_virusfilter_sophos'))
