SOURCE_DIR=	..
SOURCE_BUILD=	$(SOURCE_DIR)/build

## ======================================================================

BUILD_TARGETS=		smb.virusfilter-clamav.conf.example \
			smb.virusfilter-fsav.conf.example \
			smb.virusfilter-sophos.conf.example

## ======================================================================

include $(SOURCE_BUILD)/Makefile.common

