SOURCE_DIR=	..
SOURCE_BUILD=	$(SOURCE_DIR)/build

## ======================================================================

MAKE_DIRS=

BUILD_TARGETS=		fsavd-svconf.cmd savdid-svconf.cmd
BUILD_TARGETS_POST=

INSTALL_CMD_DIR=	$(SAMBA_DATADIR)/bin
INSTALL_CMDS=		$(BUILD_TARGETS)

## ======================================================================

include $(SOURCE_BUILD)/Makefile.common

#install:: install-exes

