SOURCE_DIR=	..
SOURCE_BUILD=	$(SOURCE_DIR)/build

## ======================================================================

DIRS=
BUILD_TARGETS= sav-utils.o
BUILD_TARGETS_POST=
INSTALL_TARGETS=

## ======================================================================

include $(SOURCE_BUILD)/Makefile.common

sav-utils.o: $(SOURCE_DIR)/include/sav-utils.h $(SAV_COMMON_HEADERS)

