SOURCE_DIR=	..
SOURCE_BUILD=	$(SOURCE_DIR)/build

## ======================================================================

BUILD_TARGETS= svf-utils.o

## ======================================================================

include $(SOURCE_BUILD)/Makefile.common

svf-utils.o:: $(SOURCE_DIR)/include/svf-utils.h $(SAV_COMMON_HEADERS)

